/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Dog;
import Controller.DogController;
import java.awt.CardLayout;
import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shahil
 */
public class DogView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DogView.class.getName());
    private CardLayout cardLayout, cardLayoutAdmin;
    private DogController controller;

    /**
     * Creates new form DogView
     */
    public DogView() {
        initComponents();
        setLocationRelativeTo(null);
        cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "loginCard");
        cardLayoutAdmin = (CardLayout) contentPanel.getLayout();
        controller = new DogController();
        controller.loadInitialData();
        controller.loadDataToTable(dogTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        logoutButtonUser = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        loginDetailsPanel = new javax.swing.JPanel();
        adminButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        navigationPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        dogsPanelButton = new javax.swing.JButton();
        usersPanelButton = new javax.swing.JButton();
        adoptionsButton = new javax.swing.JButton();
        historyPanelButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        dogsPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dogTable = new javax.swing.JTable();
        refreshTableButton = new javax.swing.JButton();
        deleteFromListButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        formDetailsPanel = new javax.swing.JPanel();
        dogIdLabel = new javax.swing.JLabel();
        idErrorPanel = new javax.swing.JPanel();
        idErrorLabel = new javax.swing.JLabel();
        dogIdField = new javax.swing.JTextField();
        dogNameLabel = new javax.swing.JLabel();
        nameErrorPanel = new javax.swing.JPanel();
        nameErrorLabel = new javax.swing.JLabel();
        dogNameField = new javax.swing.JTextField();
        dogBreedLabel = new javax.swing.JLabel();
        breedErrorPanel = new javax.swing.JPanel();
        breedErrorLabel = new javax.swing.JLabel();
        dogBreedField = new javax.swing.JTextField();
        dogAgeLabel = new javax.swing.JLabel();
        ageErrorPanel = new javax.swing.JPanel();
        ageErrorLabel = new javax.swing.JLabel();
        dogAgeField = new javax.swing.JTextField();
        dogWeightLabel = new javax.swing.JLabel();
        weightErrorPanel = new javax.swing.JPanel();
        weightErrorLabel = new javax.swing.JLabel();
        dogWeightField = new javax.swing.JTextField();
        dogGenderLabel = new javax.swing.JLabel();
        genderPanel = new javax.swing.JPanel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        dogColorLabel = new javax.swing.JLabel();
        colorErrorPanel = new javax.swing.JPanel();
        dogColorField = new javax.swing.JTextField();
        colorErrorLabel = new javax.swing.JLabel();
        dogAdoptionStatusLabel = new javax.swing.JLabel();
        adoptionStatusComboBox = new javax.swing.JComboBox<>();
        updateDogButton = new javax.swing.JButton();
        addDogButton = new javax.swing.JButton();
        clearFieldsButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        usersManagementPanel = new javax.swing.JPanel();
        adoptionsPanel = new javax.swing.JPanel();
        historyPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(1200, 800));
        mainPanel.setLayout(new java.awt.CardLayout());

        userPanel.setBackground(new java.awt.Color(255, 255, 102));

        logoutButtonUser.setText("Log out");
        logoutButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap(1099, Short.MAX_VALUE)
                .addComponent(logoutButtonUser)
                .addGap(29, 29, 29))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoutButtonUser)
                .addContainerGap(759, Short.MAX_VALUE))
        );

        mainPanel.add(userPanel, "userCard");

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setPreferredSize(new java.awt.Dimension(1200, 720));
        loginPanel.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel5, java.awt.BorderLayout.LINE_END);

        loginDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginDetailsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));

        adminButton.setText("ADMIN");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        userButton.setText("USER");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginDetailsPanelLayout = new javax.swing.GroupLayout(loginDetailsPanel);
        loginDetailsPanel.setLayout(loginDetailsPanelLayout);
        loginDetailsPanelLayout.setHorizontalGroup(
            loginDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDetailsPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        loginDetailsPanelLayout.setVerticalGroup(
            loginDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addGroup(loginDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
        );

        loginPanel.add(loginDetailsPanel, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel2, java.awt.BorderLayout.LINE_START);

        mainPanel.add(loginPanel, "loginCard");

        adminPanel.setBackground(new java.awt.Color(245, 245, 245));
        adminPanel.setPreferredSize(new java.awt.Dimension(1200, 800));
        adminPanel.setLayout(null);

        headerPanel.setBackground(new java.awt.Color(44, 62, 80));
        headerPanel.setPreferredSize(new java.awt.Dimension(1200, 80));

        logoLabel.setText("LOGO");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        adminPanel.add(headerPanel);
        headerPanel.setBounds(0, 0, 1200, 70);

        navigationPanel.setBackground(new java.awt.Color(204, 204, 204));
        navigationPanel.setMinimumSize(new java.awt.Dimension(200, 720));
        navigationPanel.setPreferredSize(new java.awt.Dimension(210, 720));

        dashboardButton.setBackground(new java.awt.Color(102, 102, 102));
        dashboardButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(220, 220, 220));
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dashboardButton.setBorderPainted(false);
        dashboardButton.setFocusPainted(false);
        dashboardButton.setPreferredSize(new java.awt.Dimension(70, 20));
        dashboardButton.setRolloverEnabled(false);
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        dogsPanelButton.setBackground(new java.awt.Color(102, 102, 102));
        dogsPanelButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        dogsPanelButton.setForeground(new java.awt.Color(220, 220, 220));
        dogsPanelButton.setText("Dogs");
        dogsPanelButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        dogsPanelButton.setPreferredSize(new java.awt.Dimension(70, 20));
        dogsPanelButton.setRolloverEnabled(false);
        dogsPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogsPanelButtonActionPerformed(evt);
            }
        });

        usersPanelButton.setBackground(new java.awt.Color(102, 102, 102));
        usersPanelButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        usersPanelButton.setText("Users");
        usersPanelButton.setPreferredSize(new java.awt.Dimension(200, 60));
        usersPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersPanelButtonActionPerformed(evt);
            }
        });

        adoptionsButton.setBackground(new java.awt.Color(102, 102, 102));
        adoptionsButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        adoptionsButton.setText("Adoptions");
        adoptionsButton.setPreferredSize(new java.awt.Dimension(200, 60));
        adoptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptionsButtonActionPerformed(evt);
            }
        });

        historyPanelButton.setBackground(new java.awt.Color(102, 102, 102));
        historyPanelButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        historyPanelButton.setText("History");
        historyPanelButton.setPreferredSize(new java.awt.Dimension(200, 60));
        historyPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyPanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dogsPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(usersPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(historyPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(adoptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(dogsPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(usersPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(adoptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(historyPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adminPanel.add(navigationPanel);
        navigationPanel.setBounds(0, 71, 200, 730);

        contentPanel.setBackground(new java.awt.Color(220, 220, 220));
        contentPanel.setForeground(new java.awt.Color(245, 245, 245));
        contentPanel.setLayout(new java.awt.CardLayout());

        dashboardPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        contentPanel.add(dashboardPanel, "dashboardCard");

        dogsPanel.setBackground(new java.awt.Color(220, 220, 220));

        tablePanel.setBackground(new java.awt.Color(220, 220, 220));
        tablePanel.setPreferredSize(new java.awt.Dimension(800, 640));

        dogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Breed", "Age", "Gender", "Weight", "Color", "AdoptionStatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(dogTable);
        if (dogTable.getColumnModel().getColumnCount() > 0) {
            dogTable.getColumnModel().getColumn(0).setMinWidth(40);
            dogTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            dogTable.getColumnModel().getColumn(0).setMaxWidth(60);
            dogTable.getColumnModel().getColumn(3).setMinWidth(40);
            dogTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            dogTable.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        refreshTableButton.setBackground(new java.awt.Color(44, 62, 80));
        refreshTableButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        refreshTableButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshTableButton.setText("Refresh");
        refreshTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTableButtonActionPerformed(evt);
            }
        });

        deleteFromListButton.setBackground(new java.awt.Color(44, 62, 80));
        deleteFromListButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        deleteFromListButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteFromListButton.setText("Delete");
        deleteFromListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFromListButtonActionPerformed(evt);
            }
        });

        searchField.setText("jTextField1");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteFromListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(refreshTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addComponent(deleteFromListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        searchField.getAccessibleContext().setAccessibleName("");
        searchField.getAccessibleContext().setAccessibleDescription("");

        formDetailsPanel.setBackground(new java.awt.Color(236, 240, 241));
        formDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Dog Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        formDetailsPanel.setForeground(new java.awt.Color(0, 0, 0));
        formDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dogIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogIdLabel.setText("ID:");
        formDetailsPanel.add(dogIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, 71, -1));

        idErrorPanel.setBackground(new java.awt.Color(236, 240, 241));
        idErrorPanel.setLayout(new java.awt.BorderLayout());

        idErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        idErrorPanel.add(idErrorLabel, java.awt.BorderLayout.PAGE_START);

        dogIdField.setBackground(new java.awt.Color(204, 204, 204));
        dogIdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogIdField.setForeground(new java.awt.Color(44, 62, 80));
        dogIdField.setActionCommand("Name");
        dogIdField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        dogIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogIdFieldActionPerformed(evt);
            }
        });
        idErrorPanel.add(dogIdField, java.awt.BorderLayout.PAGE_END);

        formDetailsPanel.add(idErrorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 40, 220, 40));

        dogNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogNameLabel.setText("Name:");
        formDetailsPanel.add(dogNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 71, -1));

        nameErrorPanel.setBackground(new java.awt.Color(236, 240, 241));
        nameErrorPanel.setLayout(new java.awt.BorderLayout());

        nameErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        nameErrorPanel.add(nameErrorLabel, java.awt.BorderLayout.PAGE_START);

        dogNameField.setBackground(new java.awt.Color(204, 204, 204));
        dogNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogNameField.setForeground(new java.awt.Color(44, 62, 80));
        dogNameField.setActionCommand("Name");
        dogNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        dogNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogNameFieldActionPerformed(evt);
            }
        });
        nameErrorPanel.add(dogNameField, java.awt.BorderLayout.PAGE_END);

        formDetailsPanel.add(nameErrorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 85, 220, 40));

        dogBreedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogBreedLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogBreedLabel.setText("Breed:");
        formDetailsPanel.add(dogBreedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, 71, -1));

        breedErrorPanel.setBackground(new java.awt.Color(236, 240, 241));
        breedErrorPanel.setLayout(new java.awt.BorderLayout());

        breedErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        breedErrorPanel.add(breedErrorLabel, java.awt.BorderLayout.PAGE_START);

        dogBreedField.setBackground(new java.awt.Color(204, 204, 204));
        dogBreedField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogBreedField.setForeground(new java.awt.Color(44, 62, 80));
        dogBreedField.setActionCommand("Breed");
        dogBreedField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        breedErrorPanel.add(dogBreedField, java.awt.BorderLayout.PAGE_END);

        formDetailsPanel.add(breedErrorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 130, 220, 40));

        dogAgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogAgeLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogAgeLabel.setText("Age");
        formDetailsPanel.add(dogAgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 55, 71, -1));

        ageErrorPanel.setBackground(new java.awt.Color(236, 240, 241));
        ageErrorPanel.setLayout(new java.awt.BorderLayout());

        ageErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        ageErrorPanel.add(ageErrorLabel, java.awt.BorderLayout.PAGE_START);

        dogAgeField.setBackground(new java.awt.Color(204, 204, 204));
        dogAgeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogAgeField.setForeground(new java.awt.Color(44, 62, 80));
        dogAgeField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        ageErrorPanel.add(dogAgeField, java.awt.BorderLayout.PAGE_END);

        formDetailsPanel.add(ageErrorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 220, 40));

        dogWeightLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogWeightLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogWeightLabel.setText("Weight");
        formDetailsPanel.add(dogWeightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 71, -1));

        weightErrorPanel.setBackground(new java.awt.Color(236, 240, 241));
        weightErrorPanel.setLayout(new java.awt.BorderLayout());

        weightErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        weightErrorPanel.add(weightErrorLabel, java.awt.BorderLayout.PAGE_START);

        dogWeightField.setBackground(new java.awt.Color(204, 204, 204));
        dogWeightField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogWeightField.setForeground(new java.awt.Color(44, 62, 80));
        dogWeightField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        weightErrorPanel.add(dogWeightField, java.awt.BorderLayout.PAGE_END);

        formDetailsPanel.add(weightErrorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 85, 220, 40));

        dogGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogGenderLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogGenderLabel.setText("Gender");
        formDetailsPanel.add(dogGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 145, 71, -1));

        genderPanel.setBackground(new java.awt.Color(236, 240, 241));

        maleRadioButton.setBackground(new java.awt.Color(236, 240, 241));
        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setForeground(new java.awt.Color(44, 62, 80));
        maleRadioButton.setText("Male");

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setForeground(new java.awt.Color(44, 62, 80));
        femaleRadioButton.setText("Female");

        javax.swing.GroupLayout genderPanelLayout = new javax.swing.GroupLayout(genderPanel);
        genderPanel.setLayout(genderPanelLayout);
        genderPanelLayout.setHorizontalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanelLayout.createSequentialGroup()
                .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(232, 232, 232))
        );
        genderPanelLayout.setVerticalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genderPanelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)))
        );

        formDetailsPanel.add(genderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 220, -1));

        dogColorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogColorLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogColorLabel.setText("Color");
        formDetailsPanel.add(dogColorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 55, 71, -1));

        colorErrorPanel.setBackground(new java.awt.Color(236, 240, 241));
        colorErrorPanel.setLayout(new java.awt.BorderLayout());

        dogColorField.setBackground(new java.awt.Color(204, 204, 204));
        dogColorField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogColorField.setForeground(new java.awt.Color(44, 62, 80));
        dogColorField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        colorErrorPanel.add(dogColorField, java.awt.BorderLayout.PAGE_END);

        colorErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        colorErrorPanel.add(colorErrorLabel, java.awt.BorderLayout.PAGE_START);

        formDetailsPanel.add(colorErrorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 40, 210, 40));

        dogAdoptionStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dogAdoptionStatusLabel.setForeground(new java.awt.Color(0, 0, 0));
        dogAdoptionStatusLabel.setText("Status");
        formDetailsPanel.add(dogAdoptionStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 96, 71, -1));

        adoptionStatusComboBox.setBackground(new java.awt.Color(204, 204, 204));
        adoptionStatusComboBox.setForeground(new java.awt.Color(44, 62, 80));
        adoptionStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adopted", "Unadopted" }));
        formDetailsPanel.add(adoptionStatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 96, 116, -1));

        updateDogButton.setBackground(new java.awt.Color(44, 62, 80));
        updateDogButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        updateDogButton.setForeground(new java.awt.Color(255, 255, 255));
        updateDogButton.setText("UPDATE");
        updateDogButton.setFocusable(false);
        updateDogButton.setPreferredSize(new java.awt.Dimension(136, 32));
        updateDogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDogButtonActionPerformed(evt);
            }
        });
        formDetailsPanel.add(updateDogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 209, -1, -1));

        addDogButton.setBackground(new java.awt.Color(44, 62, 80));
        addDogButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        addDogButton.setForeground(new java.awt.Color(255, 255, 255));
        addDogButton.setText("ADD");
        addDogButton.setPreferredSize(new java.awt.Dimension(136, 32));
        addDogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDogButtonActionPerformed(evt);
            }
        });
        formDetailsPanel.add(addDogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 209, -1, -1));

        clearFieldsButton.setBackground(new java.awt.Color(44, 62, 80));
        clearFieldsButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        clearFieldsButton.setForeground(new java.awt.Color(255, 255, 255));
        clearFieldsButton.setText("CLEAR");
        clearFieldsButton.setPreferredSize(new java.awt.Dimension(136, 32));
        clearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsButtonActionPerformed(evt);
            }
        });
        formDetailsPanel.add(clearFieldsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 209, -1, -1));

        saveButton.setBackground(new java.awt.Color(44, 62, 80));
        saveButton.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setVisible(false);
        saveButton.setPreferredSize(new java.awt.Dimension(136, 32));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        formDetailsPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 208, -1, -1));

        javax.swing.GroupLayout dogsPanelLayout = new javax.swing.GroupLayout(dogsPanel);
        dogsPanel.setLayout(dogsPanelLayout);
        dogsPanelLayout.setHorizontalGroup(
            dogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dogsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addComponent(formDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dogsPanelLayout.setVerticalGroup(
            dogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dogsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contentPanel.add(dogsPanel, "dogsCRUDCard");

        usersManagementPanel.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout usersManagementPanelLayout = new javax.swing.GroupLayout(usersManagementPanel);
        usersManagementPanel.setLayout(usersManagementPanelLayout);
        usersManagementPanelLayout.setHorizontalGroup(
            usersManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        usersManagementPanelLayout.setVerticalGroup(
            usersManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        contentPanel.add(usersManagementPanel, "usersManagementCard");
        usersManagementPanel.getAccessibleContext().setAccessibleName("");

        adoptionsPanel.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout adoptionsPanelLayout = new javax.swing.GroupLayout(adoptionsPanel);
        adoptionsPanel.setLayout(adoptionsPanelLayout);
        adoptionsPanelLayout.setHorizontalGroup(
            adoptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        adoptionsPanelLayout.setVerticalGroup(
            adoptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        contentPanel.add(adoptionsPanel, "adoptionsCard");

        historyPanel.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        contentPanel.add(historyPanel, "historyCard");

        adminPanel.add(contentPanel);
        contentPanel.setBounds(200, 70, 1000, 730);

        mainPanel.add(adminPanel, "adminCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        cardLayout.show(mainPanel, "userCard");
    }//GEN-LAST:event_userButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        cardLayout.show(mainPanel, "adminCard");
    }//GEN-LAST:event_adminButtonActionPerformed

    private void logoutButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonUserActionPerformed
        cardLayout.show(mainPanel, "loginCard");
    }//GEN-LAST:event_logoutButtonUserActionPerformed

    private void usersPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersPanelButtonActionPerformed
        cardLayoutAdmin.show(contentPanel, "usersManagementCard");
    }//GEN-LAST:event_usersPanelButtonActionPerformed

    private void historyPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyPanelButtonActionPerformed
        cardLayoutAdmin.show(contentPanel, "historyCard");
    }//GEN-LAST:event_historyPanelButtonActionPerformed

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        cardLayoutAdmin.show(contentPanel, "dashboardCard");
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void dogsPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogsPanelButtonActionPerformed
        cardLayoutAdmin.show(contentPanel, "dogsCRUDCard");
    }//GEN-LAST:event_dogsPanelButtonActionPerformed

    private void adoptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptionsButtonActionPerformed
        cardLayoutAdmin.show(contentPanel, "adoptionsCard");
    }//GEN-LAST:event_adoptionsButtonActionPerformed

    private void addDogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDogButtonActionPerformed
        // Track if any errors were found
        boolean hasErrors = false;

        // Clear all previous error highlights first
        clearAllErrorHighlights();

        // 1. Validate ID
        String idText = dogIdField.getText().trim();
        if (idText.isEmpty()) {
            errorFieldFocus(dogIdField, idErrorLabel, "ID cannot be empty.");
            hasErrors = true;
        } else {
            try {
                int id = Integer.parseInt(idText);
                if (id <= 0) {
                    errorFieldFocus(dogIdField, idErrorLabel, "ID must be positive.");
                    hasErrors = true;
                } else {
                    clearErrorField(dogIdField, idErrorLabel);
                }
            } catch (NumberFormatException e) {
                errorFieldFocus(dogIdField, idErrorLabel, "ID must be a valid number.");
                hasErrors = true;
            }
        }

        // 2. Validate Name
        String name = dogNameField.getText().trim();
        if (name.isEmpty()) {
            errorFieldFocus(dogNameField, nameErrorLabel, "Name cannot be empty.");
            hasErrors = true;
        } else {
            clearErrorField(dogNameField, nameErrorLabel);
        }

        // 3. Validate Breed
        String breed = dogBreedField.getText().trim();
        if (breed.isEmpty()) {
            errorFieldFocus(dogBreedField, breedErrorLabel, "Breed cannot be empty.");
            hasErrors = true;
        } else {
            clearErrorField(dogBreedField, breedErrorLabel);
        }

        // 4. Validate Color
        String color = dogColorField.getText().trim();
        if (color.isEmpty()) {
            errorFieldFocus(dogColorField, colorErrorLabel, "Color cannot be empty.");
            hasErrors = true;
        } else {
            clearErrorField(dogColorField, colorErrorLabel);
        }

        // 5. Validate Gender
        if (!femaleRadioButton.isSelected() && !maleRadioButton.isSelected()) {
            // Highlight gender selection area
            if (genderPanel != null) {
                genderPanel.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            }
            femaleRadioButton.setForeground(Color.RED);
            maleRadioButton.setForeground(Color.RED);
            hasErrors = true;
        } else {
            if (genderPanel != null) {
                genderPanel.setBorder(null);
            }
            femaleRadioButton.setForeground(null);
            maleRadioButton.setForeground(null);
        }

        // 6. Validate Age
        String ageText = dogAgeField.getText().trim();
        if (ageText.isEmpty()) {
            errorFieldFocus(dogAgeField, ageErrorLabel, "Age cannot be empty.");
            hasErrors = true;
        } else {
            try {
                int age = Integer.parseInt(ageText);
                if (age <= 0) {
                    errorFieldFocus(dogAgeField, ageErrorLabel, "Age must be positive.");
                    hasErrors = true;
                } else if (age > 30) {
                    errorFieldFocus(dogAgeField, ageErrorLabel, "Please enter a valid age (1-30).");
                    hasErrors = true;
                } else {
                    clearErrorField(dogAgeField, ageErrorLabel);
                }
            } catch (NumberFormatException e) {
                errorFieldFocus(dogAgeField, ageErrorLabel, "Age must be a valid number.");
                hasErrors = true;
            }
        }

        // 7. Validate Weight
        String weightText = dogWeightField.getText().trim();
        if (weightText.isEmpty()) {
            errorFieldFocus(dogWeightField, weightErrorLabel, "Weight cannot be empty.");
            hasErrors = true;
        } else {
            try {
                float weight = Float.parseFloat(weightText);
                if (weight <= 0) {
                    errorFieldFocus(dogWeightField, weightErrorLabel, "Weight must be positive.");
                    hasErrors = true;
                } else if (weight > 200) {
                    errorFieldFocus(dogWeightField, weightErrorLabel, "Please enter a valid weight (0.1-200).");
                    hasErrors = true;
                } else {
                    clearErrorField(dogWeightField, weightErrorLabel);
                }
            } catch (NumberFormatException e) {
                errorFieldFocus(dogWeightField, weightErrorLabel, "Weight must be a valid number.");
                hasErrors = true;
            }
        }

        // 8. Validate Adoption Status
        String adoptionStatus = (String) adoptionStatusComboBox.getSelectedItem();
        if (adoptionStatus == null || adoptionStatus.trim().isEmpty()) {
            adoptionStatusComboBox.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            hasErrors = true;
        } else {
            adoptionStatusComboBox.setBorder(null);
        }

        // If any errors found, show simple message and return
        if (hasErrors) {
            JOptionPane.showMessageDialog(this,
                    "Please correct the highlighted fields with errors.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);

            // Focus on first error field
            focusFirstErrorField();
            return;
        }

        // All validations passed - proceed with adding dog
        try {
            int id = Integer.parseInt(dogIdField.getText().trim());
            String gender = femaleRadioButton.isSelected() ? "Female" : "Male";
            int age = Integer.parseInt(dogAgeField.getText().trim());
            float weight = Float.parseFloat(dogWeightField.getText().trim());

            Dog newDog = new Dog(id, name, breed, adoptionStatus, age, gender, weight, color);

            if (!controller.addDog(newDog)) {
                JOptionPane.showMessageDialog(this,
                        "Dog with ID " + id + " already exists.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                controller.loadDataToTable(dogTable);
                JOptionPane.showMessageDialog(this,
                        "Dog with ID " + id + " successfully added",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected error. Please try again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addDogButtonActionPerformed

    private void updateDogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDogButtonActionPerformed
        // Ask for ID to edit
        String idInput = JOptionPane.showInputDialog(this,
                "Enter the ID of the dog to update:",
                "Edit Dog",
                JOptionPane.QUESTION_MESSAGE);

        if (idInput == null || idInput.trim().isEmpty()) {
            return;
        }

        try {
            int id = Integer.parseInt(idInput.trim());
            if (id <= 0) {
                JOptionPane.showMessageDialog(this,
                        "ID must be a positive number.",
                        "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Use your controller's viewDog method
            Dog dogToUpdate = controller.viewDog(id);
            if (dogToUpdate == null) {
                JOptionPane.showMessageDialog(this,
                        "Dog with ID " + id + " not found.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Store the ID being edited in save button's client property
            saveButton.putClientProperty("editId", id);

            // Populate form with dog data
            dogIdField.setText(String.valueOf(dogToUpdate.getId()));
            dogNameField.setText(dogToUpdate.getName());
            dogBreedField.setText(dogToUpdate.getBreed());
            dogAgeField.setText(String.valueOf(dogToUpdate.getAge()));
            dogWeightField.setText(String.valueOf(dogToUpdate.getWeight()));
            dogColorField.setText(dogToUpdate.getColor());

            if (dogToUpdate.getGender().equalsIgnoreCase("Female")) {
                femaleRadioButton.setSelected(true);
            } else {
                maleRadioButton.setSelected(true);
            }

            adoptionStatusComboBox.setSelectedItem(dogToUpdate.getAdoptionStatus());

            // Make ID field read-only during edit
            dogIdField.setEditable(false);

            // Switch button visibility
            addDogButton.setVisible(false);
            updateDogButton.setVisible(false);
            saveButton.setVisible(true);

            // Optional: Focus on first editable field
            dogNameField.requestFocus();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid numeric ID.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateDogButtonActionPerformed

    private void clearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsButtonActionPerformed
        dogIdField.setText("");
        dogNameField.setText("");
        dogBreedField.setText("");
        dogAgeField.setText("");
        dogWeightField.setText("");
        dogColorField.setText("");
        genderButtonGroup.clearSelection();
        adoptionStatusComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearFieldsButtonActionPerformed

    private void deleteFromListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFromListButtonActionPerformed
        try {
            // Show input dialog for ID
            String idInput = JOptionPane.showInputDialog(
                    this,
                    "Enter the ID of the dog to delete:",
                    "Delete Dog",
                    JOptionPane.QUESTION_MESSAGE
            );

            // If user cancels or closes the dialog
            if (idInput == null || idInput.trim().isEmpty()) {
                return;
            }

            // Validate that the input is a positive integer
            int id;
            try {
                id = Integer.parseInt(idInput);
                if (id <= 0) {
                    JOptionPane.showMessageDialog(
                            this,
                            "ID must be a positive number.",
                            "Invalid Input",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Invalid ID. Please enter a valid number.",
                        "Invalid Input",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            // Ask for confirmation before deleting
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete dog with ID: " + id,
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {
                // Attempt to delete the dog
                boolean deleted = controller.deleteDog(id);

                if (!deleted) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Dog with ID " + id + " was not found.",
                            "Not Found",
                            JOptionPane.ERROR_MESSAGE
                    );
                } else {
                    controller.loadDataToTable(dogTable);

                    JOptionPane.showMessageDialog(
                            this,
                            "Dog with ID " + id + " was successfully deleted.",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                }
            } else {
                // if user chooses not to delete
                JOptionPane.showMessageDialog(
                        this,
                        "Deletion cancelled.",
                        "Cancelled",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }

        } catch (Exception e) {
            // Catch any unexpected exceptions
            JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_deleteFromListButtonActionPerformed

    private void dogNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dogNameFieldActionPerformed

    private void dogIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dogIdFieldActionPerformed

    private void refreshTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTableButtonActionPerformed
        dogTable.repaint();
    }//GEN-LAST:event_refreshTableButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Get the ID being edited from save button's client property
        Integer editId = (Integer) saveButton.getClientProperty("editId");
        if (editId == null) {
            JOptionPane.showMessageDialog(this,
                    "Error: No dog ID found for editing.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Clear all previous error highlights
        clearAllErrorHighlights();

        // Validate all fields
        boolean hasErrors = validateAllFields();

        // If errors found, show message and return
        if (hasErrors) {
            JOptionPane.showMessageDialog(this,
                    "Please correct the highlighted fields with errors.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            focusFirstErrorField();
            return;
        }

        // All validations passed - proceed with update
        try {
            // Get all field values
            String name = dogNameField.getText().trim();
            String breed = dogBreedField.getText().trim();
            String color = dogColorField.getText().trim();
            int age = Integer.parseInt(dogAgeField.getText().trim());
            float weight = Float.parseFloat(dogWeightField.getText().trim());
            String gender = femaleRadioButton.isSelected() ? "Female" : "Male";
            String adoptionStatus = (String) adoptionStatusComboBox.getSelectedItem();

            // Create updated dog object
            Dog updatedDog = new Dog(editId, name, breed, adoptionStatus, age, gender, weight, color);

            // Call controller's updateDog method
            boolean success = controller.updateDog(editId, updatedDog);

            if (success) {
                controller.loadDataToTable(dogTable);
                JOptionPane.showMessageDialog(this,
                        "Dog updated successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                // Reset form and button visibility
                resetFormAfterSave();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to update dog. Please try again.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please enter valid numeric values for age and weight.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void errorFieldFocus(JTextField field, JLabel errorLabel, String message) {
        field.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        if (errorLabel != null) {
            errorLabel.setText(message);
            errorLabel.setForeground(Color.RED);
            errorLabel.setVisible(true);
        }
    }

    private void clearErrorField(JTextField field, JLabel errorLabel) {
        field.setBorder(BorderFactory.createLineBorder(new Color(102, 102, 102), 2));
        if (errorLabel != null) {
            errorLabel.setText("");
            errorLabel.setVisible(false);
        }
    }

    private void focusFirstErrorField() {
        if (dogIdField.getText().trim().isEmpty()) {
            dogIdField.requestFocus();
        } else if (dogNameField.getText().trim().isEmpty()) {
            dogNameField.requestFocus();
        } else if (dogBreedField.getText().trim().isEmpty()) {
            dogBreedField.requestFocus();
        } else if (dogColorField.getText().trim().isEmpty()) {
            dogColorField.requestFocus();
        } else if (dogAgeField.getText().trim().isEmpty()) {
            dogAgeField.requestFocus();
        } else if (dogWeightField.getText().trim().isEmpty()) {
            dogWeightField.requestFocus();
        }
    }

    private void clearAllErrorHighlights() {
        clearErrorField(dogIdField, idErrorLabel);
        clearErrorField(dogNameField, nameErrorLabel);
        clearErrorField(dogBreedField, breedErrorLabel);
        clearErrorField(dogColorField, colorErrorLabel);
        clearErrorField(dogAgeField, ageErrorLabel);
        clearErrorField(dogWeightField, weightErrorLabel);

        // Clear gender highlights
        if (genderPanel != null) {
            genderPanel.setBorder(null);
        }
        femaleRadioButton.setForeground(null);
        maleRadioButton.setForeground(null);

        // Clear combobox border
        adoptionStatusComboBox.setBorder(null);
    }

    private boolean validateAllFields() {
        boolean hasErrors = false;

        // 1. Validate Name
        if (dogNameField.getText().trim().isEmpty()) {
            errorFieldFocus(dogNameField, nameErrorLabel, "Name cannot be empty.");
            hasErrors = true;
        }

        // 2. Validate Breed
        if (dogBreedField.getText().trim().isEmpty()) {
            errorFieldFocus(dogBreedField, breedErrorLabel, "Breed cannot be empty.");
            hasErrors = true;
        }

        // 3. Validate Color
        if (dogColorField.getText().trim().isEmpty()) {
            errorFieldFocus(dogColorField, colorErrorLabel, "Color cannot be empty.");
            hasErrors = true;
        }

        // 4. Validate Gender
        if (!femaleRadioButton.isSelected() && !maleRadioButton.isSelected()) {
            if (genderPanel != null) {
                genderPanel.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            }
            femaleRadioButton.setForeground(Color.RED);
            maleRadioButton.setForeground(Color.RED);
            hasErrors = true;
        }

        // 5. Validate Age
        String ageText = dogAgeField.getText().trim();
        if (ageText.isEmpty()) {
            errorFieldFocus(dogAgeField, ageErrorLabel, "Age cannot be empty.");
            hasErrors = true;
        } else {
            try {
                int age = Integer.parseInt(ageText);
                if (age <= 0) {
                    errorFieldFocus(dogAgeField, ageErrorLabel, "Age must be positive.");
                    hasErrors = true;
                } else if (age > 30) {
                    errorFieldFocus(dogAgeField, ageErrorLabel, "Please enter a valid age (1-30).");
                    hasErrors = true;
                }
            } catch (NumberFormatException e) {
                errorFieldFocus(dogAgeField, ageErrorLabel, "Age must be a valid number.");
                hasErrors = true;
            }
        }

        // 6. Validate Weight
        String weightText = dogWeightField.getText().trim();
        if (weightText.isEmpty()) {
            errorFieldFocus(dogWeightField, weightErrorLabel, "Weight cannot be empty.");
            hasErrors = true;
        } else {
            try {
                float weight = Float.parseFloat(weightText);
                if (weight <= 0) {
                    errorFieldFocus(dogWeightField, weightErrorLabel, "Weight must be positive.");
                    hasErrors = true;
                } else if (weight > 200) {
                    errorFieldFocus(dogWeightField, weightErrorLabel, "Please enter a valid weight (0.1-200).");
                    hasErrors = true;
                }
            } catch (NumberFormatException e) {
                errorFieldFocus(dogWeightField, weightErrorLabel, "Weight must be a valid number.");
                hasErrors = true;
            }
        }

        // 7. Validate Adoption Status
        String adoptionStatus = (String) adoptionStatusComboBox.getSelectedItem();
        if (adoptionStatus == null || adoptionStatus.trim().isEmpty()) {
            adoptionStatusComboBox.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            hasErrors = true;
        }

        return hasErrors;
    }

    private void resetFormAfterSave() {
        // Clear the form
        dogIdField.setText("");
        dogNameField.setText("");
        dogBreedField.setText("");
        dogColorField.setText("");
        dogAgeField.setText("");
        dogWeightField.setText("");
        genderButtonGroup.clearSelection();
        adoptionStatusComboBox.setSelectedIndex(0);
        dogIdField.setEditable(true); // Re-enable ID field
        clearAllErrorHighlights();

        // Switch button visibility back
        addDogButton.setVisible(true);
        updateDogButton.setVisible(true);
        saveButton.setVisible(false);

        // Clear the stored ID
        saveButton.putClientProperty("editId", null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DogView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDogButton;
    private javax.swing.JButton adminButton;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JComboBox<String> adoptionStatusComboBox;
    private javax.swing.JButton adoptionsButton;
    private javax.swing.JPanel adoptionsPanel;
    private javax.swing.JLabel ageErrorLabel;
    private javax.swing.JPanel ageErrorPanel;
    private javax.swing.JLabel breedErrorLabel;
    private javax.swing.JPanel breedErrorPanel;
    private javax.swing.JButton clearFieldsButton;
    private javax.swing.JLabel colorErrorLabel;
    private javax.swing.JPanel colorErrorPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton deleteFromListButton;
    private javax.swing.JLabel dogAdoptionStatusLabel;
    private javax.swing.JTextField dogAgeField;
    private javax.swing.JLabel dogAgeLabel;
    private javax.swing.JTextField dogBreedField;
    private javax.swing.JLabel dogBreedLabel;
    private javax.swing.JTextField dogColorField;
    private javax.swing.JLabel dogColorLabel;
    private javax.swing.JLabel dogGenderLabel;
    private javax.swing.JTextField dogIdField;
    private javax.swing.JLabel dogIdLabel;
    private javax.swing.JTextField dogNameField;
    private javax.swing.JLabel dogNameLabel;
    private javax.swing.JTable dogTable;
    private javax.swing.JTextField dogWeightField;
    private javax.swing.JLabel dogWeightLabel;
    private javax.swing.JPanel dogsPanel;
    private javax.swing.JButton dogsPanelButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JPanel formDetailsPanel;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JPanel genderPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JButton historyPanelButton;
    private javax.swing.JLabel idErrorLabel;
    private javax.swing.JPanel idErrorPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel loginDetailsPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logoutButtonUser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel nameErrorLabel;
    private javax.swing.JPanel nameErrorPanel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton refreshTableButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateDogButton;
    private javax.swing.JButton userButton;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel usersManagementPanel;
    private javax.swing.JButton usersPanelButton;
    private javax.swing.JLabel weightErrorLabel;
    private javax.swing.JPanel weightErrorPanel;
    // End of variables declaration//GEN-END:variables
}
